package api

import "net/http"

func (h *Handler) handleRuleCatalog(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, buildCatalog())
}

func buildCatalog() catalogResponse {
	return catalogResponse{
		Version: "1.0",
		Types: []catalogType{
			{
				Type:                "SPEC_LIMIT_VIOLATION",
				Title:               "Spec Limit Violation",
				Description:         "Check latest value against spec or control limits",
				Phase:               1,
				Category:            "spec_limit",
				RequiresBaseline:    false,
				SupportsSubgrouping: false,
				MinData:             minDataSpec{MinBaselineSamples: 0, MinBaselineSubgroups: 0, MinEvalSamples: 1},
				RequiredInputs:      []string{"specLimits"},
				ConfigSchema: configSchema{Fields: []configField{
					{
						Key:      "mode",
						Label:    "Mode",
						Type:     "enum",
						Required: true,
						Default:  "spec",
						EnumOptions: []string{"spec", "control", "both"},
					},
					{
						Key:      "specLimits.usl",
						Label:    "USL",
						Type:     "number",
						Required: false,
					},
					{
						Key:      "specLimits.lsl",
						Label:    "LSL",
						Type:     "number",
						Required: false,
					},
					{
						Key:      "controlLimits.ucl",
						Label:    "UCL",
						Type:     "number",
						Required: false,
					},
					{
						Key:      "controlLimits.lcl",
						Label:    "LCL",
						Type:     "number",
						Required: false,
					},
					{
						Key:      "epsilon",
						Label:    "Tolerance",
						Type:     "number",
						Required: false,
						Default:  0,
					},
				}},
				Examples: []catalogExample{{Name: "Default", Config: map[string]any{"mode": "spec", "specLimits": map[string]any{"usl": 100, "lsl": 10}}}},
			},
			{
				Type:                "SHEWHART_3SIGMA",
				Title:               "3σ Spec Limits (Shewhart)",
				Description:         "Compute μ and σ from baseline; flag points outside μ±3σ",
				Phase:               1,
				Category:            "shewhart",
				RequiresBaseline:    true,
				SupportsSubgrouping: false,
				MinData:             minDataSpec{MinBaselineSamples: 20, MinBaselineSubgroups: 0, MinEvalSamples: 1},
				RequiredInputs:      []string{"baselineSelector"},
				ConfigSchema: configSchema{Fields: []configField{
					{
						Key:      "baseline.selector",
						Label:    "Baseline",
						Type:     "baselineSelector",
						Required: true,
						Default:  map[string]any{"kind": "lastN", "value": 100},
						HelpText: "Choose stable baseline period",
					},
					{
						Key:      "minBaselineN",
						Label:    "Min Baseline N",
						Type:     "number",
						Required: false,
						Default:  20,
					},
				}},
				Examples: []catalogExample{{Name: "Default", Config: map[string]any{"sigmaMultiplier": 3, "minBaselineN": 20}}},
			},
			{
				Type:                "SHEWHART_2SIGMA",
				Title:               "2σ Spec Limits (Shewhart)",
				Description:         "Compute μ and σ from baseline; flag points outside μ±2σ",
				Phase:               1,
				Category:            "shewhart",
				RequiresBaseline:    true,
				SupportsSubgrouping: false,
				MinData:             minDataSpec{MinBaselineSamples: 20, MinBaselineSubgroups: 0, MinEvalSamples: 1},
				RequiredInputs:      []string{"baselineSelector"},
				ConfigSchema: configSchema{Fields: []configField{
					{
						Key:      "baseline.selector",
						Label:    "Baseline",
						Type:     "baselineSelector",
						Required: true,
						Default:  map[string]any{"kind": "lastN", "value": 100},
						HelpText: "Choose stable baseline period",
					},
					{
						Key:      "minBaselineN",
						Label:    "Min Baseline N",
						Type:     "number",
						Required: false,
						Default:  20,
					},
				}},
				Examples: []catalogExample{{Name: "Default", Config: map[string]any{"sigmaMultiplier": 2, "minBaselineN": 20}}},
			},
			{
				Type:                "RANGE_CHART_R",
				Title:               "Range Chart (R)",
				Description:         "Compute subgroup range (R) and compare against D3/D4 limits",
				Phase:               1,
				Category:            "range_chart",
				RequiresBaseline:    true,
				SupportsSubgrouping: true,
				MinData:             minDataSpec{MinBaselineSamples: 0, MinBaselineSubgroups: 10, MinEvalSamples: 1},
				RequiredInputs:      []string{"baselineSelector", "subgrouping"},
				ConfigSchema: configSchema{Fields: []configField{
					{
						Key:      "baseline.selector",
						Label:    "Baseline",
						Type:     "baselineSelector",
						Required: true,
						Default:  map[string]any{"kind": "lastN", "value": 100},
					},
					{
						Key:      "subgrouping.subgroupSize",
						Label:    "Subgroup Size",
						Type:     "number",
						Required: true,
						Default:  5,
						HelpText: "Supported sizes: 2-10",
					},
					{
						Key:      "subgrouping.kind",
						Label:    "Subgrouping",
						Type:     "enum",
						Required: true,
						Default:  "column",
						EnumOptions: []string{"column", "consecutive"},
					},
					{
						Key:      "subgrouping.column",
						Label:    "Subgroup Column",
						Type:     "column",
						Required: false,
						VisibleWhen: &visibleWhen{Field: "subgrouping.kind", Is: "column"},
					},
					{
						Key:      "minBaselineSubgroups",
						Label:    "Min Baseline Subgroups",
						Type:     "number",
						Required: false,
						Default:  10,
					},
				}},
				Examples: []catalogExample{{Name: "Default", Config: map[string]any{"subgroupSize": 5, "minBaselineSubgroups": 10}}},
			},
			{
				Type:                "TREND_6_POINTS",
				Title:               "6-Point Trend",
				Description:         "Flags 6 consecutive increases or decreases",
				Phase:               1,
				Category:            "trend",
				RequiresBaseline:    false,
				SupportsSubgrouping: false,
				MinData:             minDataSpec{MinBaselineSamples: 0, MinBaselineSubgroups: 0, MinEvalSamples: 6},
				RequiredInputs:      []string{},
				ConfigSchema: configSchema{Fields: []configField{
					{
						Key:      "windowSize",
						Label:    "Window Size",
						Type:     "number",
						Required: false,
						Default:  6,
					},
					{
						Key:      "epsilon",
						Label:    "Epsilon",
						Type:     "number",
						Required: false,
						Default:  0,
					},
					{
						Key:      "requireConsecutiveTimestamps",
						Label:    "Require consecutive timestamps",
						Type:     "boolean",
						Required: false,
						Default:  true,
					},
				}},
				Examples: []catalogExample{{Name: "Default", Config: map[string]any{"windowSize": 6, "epsilon": 0, "requireConsecutiveTimestamps": true}}},
			},
			{
				Type:                "TPA",
				Title:               "Trend Projection (TPA)",
				Description:         "Linear regression on recent points to project slope/time-to-spec",
				Phase:               1,
				Category:            "tpa",
				RequiresBaseline:    false,
				SupportsSubgrouping: false,
				MinData:             minDataSpec{MinBaselineSamples: 0, MinBaselineSubgroups: 0, MinEvalSamples: 3},
				RequiredInputs:      []string{"threshold"},
				ConfigSchema: configSchema{Fields: []configField{
					{
						Key:      "windowN",
						Label:    "Window N",
						Type:     "number",
						Required: true,
						Default:  5,
					},
					{
						Key:      "regressionTimeBasis",
						Label:    "Regression Time Basis",
						Type:     "enum",
						Required: false,
						Default:  "timestamp",
						EnumOptions: []string{"timestamp", "index"},
					},
					{
						Key:      "slopeThreshold",
						Label:    "Slope Threshold",
						Type:     "number",
						Required: false,
					},
					{
						Key:      "timeToSpecThreshold",
						Label:    "Time-to-Spec Threshold",
						Type:     "number",
						Required: false,
					},
					{
						Key:      "requireSpecLimits",
						Label:    "Require Spec Limits",
						Type:     "boolean",
						Required: false,
						Default:  false,
					},
				}},
				Examples: []catalogExample{{Name: "Default", Config: map[string]any{"windowN": 5, "regressionTimeBasis": "timestamp", "slopeThreshold": 0.5}}},
			},
		},
	}
}
